### ISSUE TITLE
arsenal freez/gamecrash

### ISSUE THREAD

**Issue by mindbl4ster** [TaskForce47/Liberation#65]
https://forum.armasim.de/forum/index.php/Thread/4871-Arsenal-Freeze/?postID=25018#post25018

**Comment by TheWillard** [comment]
Mit XLA Arsenal passiert das nicht (meiner Erfahrung nach).

**Comment by mindbl4ster** [comment]
thx, werd ich ausprobiern

**Comment by mindbl4ster** [comment]
xla integrated
